Update build_test_deploy.yml

diff --git a/.github/workflows/build_test_deploy.yml b/.github/workflows/build_test_deploy.yml
--- a/.github/workflows/build_test_deploy.yml
+++ b/.github/workflows/build_test_deploy.yml
@@ -31,11 +31,11 @@ jobs:
       - name: Test and coverage report with unittest
         run: |
           coverage run Tests.py
-          coverage report --data-file .coverage
-          # takes the last element from the previous statement - in this case, the overall code coverage.
-          coverage_percent=$(coverage report --fail-under=75  | tail -n 1 | awk '{print $NF}')
-          # fails if the code coverage is less than 75% so that the image is NOT pushed to Docker
-          if [ $(echo "$coverage_percent < 75" | bc) -eq 1 ]; then
+          # exit 1 if coverage is under 75%
+          coverage report --fail-under=75 --show-missing
+          # takes exit status of previous line - exits workflow if coverage failed
+          # this way, the image is not pushed to Docker
+          if [ $? -ne 0 ]; then
             exit 1
           fi
       - name: Checkout
